"""add is_countryside to orders

Revision ID: 171f397b8ba0
Revises: fd4d0b2c143f
Create Date: 2026-03-31 17:13:55.573669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171f397b8ba0'
down_revision: Union[str, Sequence[str], None] = 'fd4d0b2c143f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_countryside', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_countryside')
    # ### end Alembic commands ###
