"""add_location_confirmed_and_driver_locations

Revision ID: a24dab69d776
Revises: 21e42031694b
Create Date: 2026-04-01 12:03:51.594631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24dab69d776'
down_revision: Union[str, Sequence[str], None] = '21e42031694b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_locations',
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.add_column('orders', sa.Column('location_confirmed', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('location_confirmed_by', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('location_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'location_confirmed_at')
    op.drop_column('orders', 'location_confirmed_by')
    op.drop_column('orders', 'location_confirmed')
    op.drop_table('driver_locations')
    # ### end Alembic commands ###
