"""initial schema with timestamps

Revision ID: fd4d0b2c143f
Revises: 
Create Date: 2026-03-30 18:00:59.624134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4d0b2c143f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('sales_number', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('sales_id', sa.String(), nullable=False),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('route_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('exchange_sales_id', sa.String(), nullable=True),
    sa.Column('return_sales_id', sa.String(), nullable=True),
    sa.Column('is_pay', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('is_country', sa.Boolean(), nullable=True),
    sa.Column('is_download', sa.Boolean(), nullable=True),
    sa.Column('is_integration', sa.Boolean(), nullable=True),
    sa.Column('is_start_driver', sa.Boolean(), nullable=True),
    sa.Column('is_direct_pay', sa.Boolean(), nullable=True),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.Column('status_color', sa.String(), nullable=True),
    sa.Column('wfm_status_id', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sales_number'),
    sa.UniqueConstraint('sales_id')
    )
    op.create_index('ix_orders_delivery_date', 'orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: drop statements for routes/users/geocode_cache/route_stops/spatial_ref_sys
    # were removed — those tables belong to other services sharing this Neon database.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_driver_id'), table_name='orders')
    op.drop_index('ix_orders_delivery_date', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
